name: flutter_color_picker_plus_example
description: A flutter_color_picker_plus example Flutter project.
version: 1.0.1+1

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  flutter_color_picker_plus:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

environment:
  sdk: '>=3.1.0 <4.0.0'
